### ISSUE TITLE
ハンバーガーメニューがうまく表示されない

### ISSUE THREAD

**Issue by kasunasa** [kasunasa/hambueger#1]
<img width="532" alt="CleanShot 2023-08-29 at 12 52 49@2x" src="https://github.com/kasunasa/hambueger/assets/137396545/afdcacc5-a720-4132-814d-eed211f59c82">

ハンバーガーメニューの３本線がうまく表示されず、原因を特定願いたいです。

こちらの動画を参考にしました
`https://www.youtube.com/watch?v=Tpoa6RWttoM&t=909s`

**Comment by genta-kawabata** [comment]
toggle-btn セレクタは class だと思いますので、
↓こちらの先頭に".（ドット）"が必要です
https://github.com/kasunasa/hambueger/blob/91da1d0130687cd6b8a9e0056222fb3b52c72ec4/CSS#L55

**Comment by kasunasa** [comment]
コード解決しました！
ありがとうございました！
